apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: default

resources:
  - odoo-configmap.yaml
  - odoo-deployment.yaml
  - odoo-service.yaml
  - odoo-secret.yaml
  - odoo-hpa.yaml
  - odoo-pvc.yaml
  - odoo-rbac.yaml
  - postgres-secret-sync.yaml
  - odoo-backup-cronjob.yaml
  - odoo-s3-secret.yaml
  - odoo-r2-secret.yaml
