apiVersion: v1
kind: Secret
metadata:
  name: odoo-r2-secret
  namespace: default
type: Opaque
stringData:
  R2_ACCESS_KEY_ID: "" # CHANGE
  R2_SECRET_ACCESS_KEY: "" # CHANGE
  R2_ACCOUNT_ID: "" # CHANGE
  R2_BUCKET: "" # CHANGE
