apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: odoo-filestore
spec:
  accessModes:
    - ReadWriteMany # Allows multiple pods to read and write
  resources:
    requests:
      storage: 10Gi # Adjust size as needed
  storageClassName: azurefile-csi # Use Azure Files for ReadWriteMany support
