---
apiVersion: v1
kind: Service
metadata:
  name: odoo
spec:
  type: ClusterIP
  ports:
    - name: web
      port: 80
      targetPort: 8069
    - name: websocket
      port: 8072
      targetPort: 8072
  selector:
    app: odoo
