apiVersion: v1
kind: ServiceAccount
metadata:
  name: odoo-sa
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: postgres-secrets-reader
  namespace: postgres
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    resourceNames: ["postgres-app"]
    verbs: ["get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: default-secrets-manager
  namespace: default
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["create", "update", "patch", "get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: odoo-postgres-secrets
  namespace: postgres
subjects:
  - kind: ServiceAccount
    name: odoo-sa
    namespace: default
roleRef:
  kind: Role
  name: postgres-secrets-reader
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: odoo-default-secrets
  namespace: default
subjects:
  - kind: ServiceAccount
    name: odoo-sa
    namespace: default
roleRef:
  kind: Role
  name: default-secrets-manager
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: secret-reader
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: odoo-sa-secret-reader
subjects:
  - kind: ServiceAccount
    name: odoo-sa
    namespace: default
roleRef:
  kind: ClusterRole
  name: secret-reader
  apiGroup: rbac.authorization.k8s.io
