apiVersion: batch/v1
kind: Job
metadata:
  name: postgres-secret-sync
  namespace: default
spec:
  template:
    spec:
      serviceAccountName: odoo-sa
      restartPolicy: OnFailure
      containers:
        - name: kubectl
          image: bitnami/kubectl
          command:
            - /bin/bash
            - -c
            - |
              # Get postgres-app secret from postgres namespace
              SECRET=$(kubectl get secret postgres-app -n postgres -o json)

              # Remove namespace-specific metadata
              SECRET=$(echo $SECRET | jq 'del(.metadata.namespace,.metadata.resourceVersion,.metadata.uid,.metadata.creationTimestamp,.metadata.selfLink,.metadata.ownerReferences)')

              # Apply the secret to default namespace
              echo $SECRET | kubectl apply -f -
